name: ✨ Feature Request
description: Suggest a new feature or enhancement for Actionbook
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

        Please check if similar feature requests already exist.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing feature requests
          required: true
        - label: I have checked the roadmap/milestones
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which component should this feature be added to?
      options:
        - "SDK (@actionbookdev/sdk)"
        - "MCP Server (@actionbookdev/mcp)"
        - "Action Builder"
        - "Knowledge Builder"
        - "API Service"
        - "Database (services/db)"
        - "Website (apps/website)"
        - "Documentation"
        - "Platform-wide"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Tool/Method
        - Browser Automation Enhancement
        - MCP Protocol Extension
        - Action Recording Enhancement
        - Scenario Knowledge Extraction
        - API Enhancement
        - Performance Improvement
        - Developer Experience (DX)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, when working with Actionbook...
        This causes issues because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to see a new feature that...
        This would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        I've looked at...
        But they don't work because...
    validations:
      required: false

  - type: textarea
    id: api-design
    attributes:
      label: API Design Proposal (Optional)
      description: If applicable, propose an API design
      placeholder: |
        ```typescript
        // Proposed API
        const result = await actionbook.newFeature({
          option1: 'value',
          option2: true
        });
        ```
      render: typescript
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Significantly impacts productivity
        - Medium - Would be nice to have
        - Low - Minor convenience
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Use Case 1: When building action libraries for e-commerce sites...
        Use Case 2: In high-traffic production environments with AI agents...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Reduce token usage by X%
        - Improve action accuracy
        - Simplify developer workflow
        - Better AI agent integration
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        Links to similar implementations:
        - https://example.com/similar-feature

        Related issues:
        - #123
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature and submit a PR
          required: false
