name: ⚡ Performance Issue
description: Report performance problems or optimization opportunities
title: "[Performance]: "
labels: ["performance", "needs-investigation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Report performance bottlenecks or optimization opportunities in Actionbook.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component has the performance issue?
      options:
        - "SDK (@actionbookdev/sdk)"
        - "MCP Server (@actionbookdev/mcp)"
        - "Action Builder"
        - "Knowledge Builder"
        - "API Service"
        - "Database (services/db)"
        - "Website (apps/website)"
        - "Platform-wide"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    id: performance-area
    attributes:
      label: Performance Area
      description: Which area is affected?
      options:
        - Token Usage / Cost Optimization
        - Browser Automation Speed
        - Action Recording Performance
        - Knowledge Extraction Speed
        - API Response Time
        - Database Query Performance
        - Memory Usage
        - Network Latency
        - Cold Start Performance
        - Vector Search Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: current-performance
    attributes:
      label: Current Performance Metrics
      description: Provide baseline metrics
      placeholder: |
        - Response time: 5-10 seconds
        - Memory usage: 500MB
        - Token usage: 60K-120K per operation
        - Database query time: 2 seconds
        - Action recording time: 30 seconds per action
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance do you expect?
      placeholder: |
        - Response time: < 2 seconds
        - Memory usage: < 200MB
        - Token usage: 3K-5K per operation (80% reduction)
        - Database query time: < 500ms
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How to reproduce the performance issue
      placeholder: |
        1. Initialize component with...
        2. Perform operation...
        3. Measure using...
    validations:
      required: true

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data
      description: Include profiling or benchmark results if available
      placeholder: |
        Attach screenshots, flame graphs, or benchmark results

        Example:
        - Chrome DevTools Performance Profile
        - Node.js CPU/Memory profile
        - Database EXPLAIN output
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        - Component version: x.x.x
        - Node.js version: x.x.x
        - Database: PostgreSQL x.x.x
        - Browser: Chrome x.x.x
        - OS: macOS/Windows/Linux
        - Memory: 8GB/16GB/32GB
    validations:
      required: false

  - type: textarea
    id: optimization-ideas
    attributes:
      label: Optimization Ideas
      description: Any ideas for optimization?
      placeholder: |
        - Implement caching for frequently accessed actions
        - Reduce API calls by batching requests
        - Use streaming instead of full response loading
        - Optimize database indexes
        - Implement connection pooling
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: How does this performance issue impact your usage?
      placeholder: |
        - Production deployment blocked
        - Increased costs due to token usage
        - Poor user experience
        - Cannot scale to required load
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Workload characteristics
        - Traffic patterns
        - Data volume
        - Concurrent operations
    validations:
      required: false
